Aerocobra text emotions
expertspec/expert pull request #41
Opened 2023-06-21 12:48 UTC by Besenok-13

Толя или Ваня

2023-06-23 12:57 UTC, mdvdv requested changes

2023-06-23 12:57 UTC, mdvdv commented on expert/core/insult/README.md
> +The module analyzes a passage of text and determines whether or not it contains sarcasm or insults. The main class, which is called Linear_insult_pred and located in the <b>insult_detector.py</b>. th
Не верно использован тэг < b > < / b >. В третьем предложении он не закрывается. Также стоит еще раз проверить заглавные буквы, орфографические и синтаксические ошибки

2023-06-30 09:30 UTC, mdvdv submitted a review, later dismissed

2023-07-03 08:07 UTC, Lameus reviewed
Основной класс должен получать на вход пути к видео, тексту и прочему (по аналогии с другими модулями) и возвращать путь к json файлу с отчетом при вызове функции get_... (insult) вместо predict

2023-07-11 08:57 UTC, Lameus approved these changes

2023-07-14 09:05 UTC, mdvdv approved these changes

2023-07-14 09:05 UTC, merged