Add evasiveness module
expertspec/expert pull request #43
Opened 2023-06-21 14:42 UTC by KomarovaAA

2023-06-23 11:46 UTC, mdvdv requested changes

2023-06-23 11:46 UTC, mdvdv commented on expert/core/evasiveness/rf_evas_model.pickle
Размести веса в директории expert/core/evasiveness/weights/

2023-06-23 11:46 UTC, mdvdv commented on expert/core/evasiveness/rf_evas_model_ru.pickle
Размести веса в директории expert/core/evasiveness/weights/

2023-06-23 11:46 UTC, mdvdv commented on expert/core/evasiveness/models.py
> +class QuestionStatement:
Укажи краткими комментариями в каком случае стоит использовать эту модель, зачем она нужна

2023-06-30 09:27 UTC, mdvdv submitted a review, later dismissed

2023-07-03 07:43 UTC, Lameus commented
Для единообразия: в остальных модулях язык проверяется слелующим образом: 
if lang not in ["en", "ru"]:
    raise NotImplementedError("'lang' must be 'en' or 'ru'.")
Сейчас в models get_models через assert. В целом, можно перенести эту функцию в __init__ evasiveness_analysis.py, так как используется только единожды для получения моделей
Не хватает префикса в названии файла models.py, например evas_models
 "not evasive" пробел заменить на "_"
Также в get_evasiveness есть print(dialogue). По идее, в библотеке нет print'ов

2023-07-03 07:45 UTC, Lameus reviewed
Для единообразия: в остальных модулях язык проверяется слелующим образом:
if lang not in ["en", "ru"]:
raise NotImplementedError("'lang' must be 'en' or 'ru'.")
Сейчас в models get_models через assert. В целом, можно перенести эту функцию в init evasiveness_analysis.py, так как используется только единожды для получения моделей
Не хватает префикса в названии файла models.py, например evas_models
"not evasive" пробел заменить на "_"
Также в get_evasiveness есть print(dialogue). По идее, в библотеке нет print'ов

2023-07-04 07:08 UTC, Lameus approved these changes

2023-07-04 07:12 UTC, merged