Samigulin terms
expertspec/expert pull request #44
Opened 2023-07-04 15:57 UTC by TimurSamigulin

2023-07-07 08:19 UTC, mdvdv requested changes

2023-07-07 08:19 UTC, mdvdv commented on expert/core/terms_extractor/README.md
> +# Terms Extractor
Описать что означет каждый архив в data

2023-07-07 08:19 UTC, mdvdv commented on expert/core/terms_extractor/app/extractor.py
> +from typing import Dict, List
Переименовать из app в более нейтральное название: tools, utils, другое. App обычно используется для всей сборки, а здесь представлен  даже не модуль, а каталог с утилитами.
Перевести докстринги в Google Style формат, на английском языке

2023-07-07 08:19 UTC, mdvdv commented on expert/core/terms_extractor/app/text_preprocessing.py
> +import re
Перевести докстринги в Google Style формат, на английском языке

2023-07-07 08:19 UTC, mdvdv commented on expert/core/terms_extractor/app/work_with_terms.py
> +import pickle
Перевести докстринги в Google Style формат, на английском языке

2023-07-07 08:19 UTC, mdvdv commented on expert/core/terms_extractor/get_terms.py
> +from typing import Dict, List
Перевести докстринги в Google Style формат, на английском языке

2023-07-14 16:35 UTC, Lameus requested changes
Требуется удалить папку app, которая дублируется в tools

2023-07-14 16:41 UTC, TimurSamigulin commented
> Требуется удалить папку app, которая дублируется в tools

Поправил, забыл что удаление через rm, а не add коммититься на гит

2023-07-17 10:01 UTC, mdvdv requested changes

2023-07-17 10:01 UTC, mdvdv commented on expert/core/terms_extractor/tools/work_with_terms.py
> +        Dictionary.RU3_5: "data/ru_term_index_3.5.pickle",
Загрузка словарей не тестировалась в рамках всей библиотеки. Указан относительный, а не абсолютный путь. Файлы не загрузяться туда, куда требуется, если вызывать метод из внешнего каталога

2023-07-17 10:01 UTC, mdvdv commented on expert/core/terms_extractor/README.md
Добавить __init__.py в каталог terms_extractor и все его подкаталоги

2023-07-19 11:07 UTC, mdvdv approved these changes

2023-07-20 07:38 UTC, Lameus approved these changes

2023-07-20 07:38 UTC, merged